### ISSUE TITLE
Usage of deprecated theme spacing attributes

### ISSUE THREAD

**Issue by zeved** [helfi92/material-ui-treeview#42] opened 2019-08-29 18:04 UTC
```
Warning: Material-UI: theme.spacing.unit usage has been deprecated.
It will be removed in v5.
You can replace `theme.spacing.unit * y` with `theme.spacing(y)`
```

material-ui 4.3.2

**Comment by helfi92** [comment] 2019-08-30 16:46
This error will go away once we migrate this to the v4 version of material-ui. There's an issue filed for this but I don't think anyone is working on it atm. Duplicate of https://github.com/helfi92/material-ui-treeview/issues/36.

**Closed by helfi92** 2019-08-30 16:46 UTC
